In [1]:
!pip install --upgrade nueramic-mathml

  Attempting uninstall: nueramic-mathml
    Found existing installation: nueramic-mathml 0.0.1.1
    Uninstalling nueramic-mathml-0.0.1.1:
      Successfully uninstalled nueramic-mathml-0.0.1.1
You should consider upgrading via the '/usr/local/bin/python3.9 -m pip install --upgrade pip' command.


In [2]:
from nueramic_mathml import *

In [6]:
!pip3 install torch torchvision torchaudio

You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip' command.


In [3]:
import torch


def func(x): return -torch.e ** (- x[0] ** 2 - x[1] ** 2)


x_0 = torch.tensor([1, 2])
solution = gd_optimal(func, x_0)
print(solution[0])
#{'point': array([9.21321369e-08, 1.84015366e-07]), 'f_value': -0.9999999999999577}

tensor([9.2069e-08, 1.8405e-07], dtype=torch.float64)


In [12]:
def f(x): return -5 * x ** 5 + 4 * x ** 4 - 12 * x ** 3 + 11 * x ** 2 - 2 * x + 1


bound = torch.tensor([-0.5, 0.5])
bfgs(f,
     bound)

RuntimeError: expand(torch.DoubleTensor{[2]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1)

In [15]:
def func(x): return x[0] ** 2 + x[1] ** 2
x_0 = torch.tensor([1, 2])
solution = gd_constant(func, x_0)
print(solution[0])

tensor([1.9156e-06, 3.8312e-06], dtype=torch.float64)


In [16]:
def func(x): return x[0] ** 2 + x[1] ** 2
x_0 = torch.tensor([1, 2])
solution = gd_frac(func, x_0)
print(solution[0])

tensor([1.9156e-06, 3.8312e-06], dtype=torch.float64)


In [17]:
def func(x): return -torch.exp(- x[0] ** 2 - x[1] ** 2)
x_0 = torch.tensor([1, 2])
solution = gd_optimal(func, x_0)
print(solution[0])

tensor([9.2070e-08, 1.8405e-07], dtype=torch.float64)


In [18]:
def func(x): return 10 * x[0] ** 2 + x[1] ** 2 / 5
x_0 = torch.tensor([1, 2])
solution = nonlinear_cgm(func, x_0)
print(solution[0])

tensor([6.9846e+25, 4.2454e+26], dtype=torch.float64)


In [20]:
log_barrier_solver(lambda x: (x[0] + 0.5) ** 2 + (x[1] - 0.5) ** 2, torch.tensor([0.9, 0.1]),
                           [lambda x: x[0], lambda x: 1 - x[0], lambda x: x[1], lambda x: 1 - x[1]])[0]

tensor([0.0032, 0.5000], dtype=torch.float64)

In [26]:
constrained_lagrangian_solver(lambda x: (x[0] + 0.5) ** 2 + (x[1] - 0.5) ** 2, torch.tensor([0.1, 0.1]),
                            [lambda x: x[0] - 1])[0]

tensor([1.0540, 0.5000], dtype=torch.float64)

In [5]:
primal_dual_interior(lambda x: (x[0] + 0.5) ** 2 + (x[1] - 0.5) ** 2, torch.tensor([0.9, 0.1]),
                        [lambda x: x[0], lambda x: 1 - x[0], lambda x: x[1], lambda x: 1 - x[1]])[0]

tensor([1.9910e-04, 5.0000e-01], dtype=torch.float64)